climat = [
  [0,"fr","Sylvie GOULARD","ADLE","Modem","pour"],
  [1,"fr","Corinne LEPAGE","ADLE","Cap21","pour"],
  [2,"fr","Jean-Luc BENNAHMIAS","ADLE","Modem","pour"],
  [3,"fr","Marielle de SARNEZ","ADLE","Modem","pour"],
  [4,"fr","Nathalie GRIESBECK","ADLE","Modem","pour"],
  [5,"fr","Robert ROCHEFORT","ADLE","Modem","pour"],
  [6,"fr","Philippe de VILLIERS","EFD","MPF","contre"],
  [7,"fr","Jacky HÉNIN","GUE/NGL","FdG","absent"],
  [8,"fr","Jean-Luc MÉLENCHON","GUE/NGL","FdG","pour"],
  [9,"fr","Marie-Christine VERGIAT","GUE/NGL","FdG","abstention"],
  [10,"fr","Patrick LE HYARIC","GUE/NGL","FdG","pour"],
  [11,"fr","Younous OMARJEE","GUE/NGL","FdG","pour"],
  [12,"fr","Jean-Marie LE PEN","NI","FN","absent"],
  [13,"fr","Marine LE PEN","NI","FN","contre"],
  [14,"fr","Bruno GOLLNISCH","NI","FN","na"],
  [15,"fr","Michel DANTIN","PPE","UMP","contre"],
  [16,"fr","Christine DE VEYRAC","PPE","UDI","pour"],
  [17,"fr","Dominique VLASTO","PPE","UMP","na"],
  [18,"fr","Jean ROATTA","PPE","UMP","pour"],
  [19,"fr","Brice HORTEFEUX","PPE","UMP","contre"],
  [20,"fr","Constance LE GRIP","PPE","UMP","contre"],
  [21,"fr","Gaston FRANCO","PPE","UMP","contre"],
  [22,"fr","Jean-Paul GAUZÈS","PPE","UMP","contre"],
  [23,"fr","Jean-Pierre AUDY","PPE","UMP","contre"],
  [24,"fr","Marielle GALLO","PPE","UDI","pour"],
  [25,"fr","Agnès LE BRUN","PPE","UMP","contre"],
  [26,"fr","Alain CADEC","PPE","UMP","contre"],
  [27,"fr","Alain LAMASSOURE","PPE","UMP","contre"],
  [28,"fr","Arnaud DANJEAN","PPE","UMP","contre"],
  [29,"fr","Dominique RIQUET","PPE","PR/UDI","pour"],
  [30,"fr","Elisabeth MORIN-CHARTIER","PPE","UMP","contre"],
  [31,"fr","Franck PROUST","PPE","UMP","contre"],
  [32,"fr","Françoise GROSSETÊTE","PPE","UMP","contre"],
  [33,"fr","Jean-Marie CAVADA","PPE","NC","pour"],
  [34,"fr","Joseph DAUL","PPE","UMP","contre"],
  [35,"fr","Marie-Thérèse SANCHEZ-SCHMID","PPE","UMP","contre"],
  [36,"fr","Maurice PONGA","PPE","UMP","contre"],
  [37,"fr","Michèle STRIFFLER","PPE","PR/UDI","na"],
  [38,"fr","Nora BERRA","PPE","UMP","na"],
  [39,"fr","Philippe BOULLAND","PPE","UMP","contre"],
  [40,"fr","Philippe JUVIN","PPE","UMP","contre"],
  [41,"fr","Rachida DATI","PPE","UMP","contre"],
  [42,"fr","Sophie AUCONIE","PPE","UDI","pour"],
  [43,"fr","Tokia SAÏFI","PPE","UMP","contre"],
  [44,"fr","Véronique MATHIEU HOUILLON","PPE","UMP","contre"],
  [45,"fr","Henri WEBER","S&D","PS","pour"],
  [46,"fr","Liem HOANG NGOC","S&D","PS","pour"],
  [47,"fr","Harlem DÉSIR","S&D","PS","na"],
  [48,"fr","Eric ANDRIEU","S&D","PS","pour"],
  [49,"fr","Bernadette VERGNAUD","S&D","PS","pour"],
  [50,"fr","Catherine TRAUTMANN","S&D","PS","pour"],
  [51,"fr","Christine REVAULT D'ALLONNES BONNEFOY","S&D","PS","pour"],
  [52,"fr","Françoise CASTEX","S&D","PS","pour"],
  [53,"fr","Gilles PARGNEAUX","S&D","PS","pour"],
  [54,"fr","Isabelle THOMAS","S&D","PS","pour"],
  [55,"fr","Jean Louis COTTIGNY","S&D","PS","pour"],
  [56,"fr","Patrice TIROLIEN","S&D","PS","na"],
  [57,"fr","Pervenche BERÈS","S&D","PS","pour"],
  [58,"fr","Sylvie GUILLAUME","S&D","PS","pour"],
  [59,"fr","Catherine GRÈZE","Verts/ALE","EELV","pour"],
  [60,"fr","Hélène FLAUTRE","Verts/ALE","EELV","pour"],
  [61,"fr","Karim ZÉRIBI","Verts/ALE","EELV","pour"],
  [62,"fr","Malika BENARAB-ATTOU","Verts/ALE","EELV","na"],
  [63,"fr","Sandrine BÉLIER","Verts/ALE","EELV","pour"],
  [64,"fr","Daniel COHN-BENDIT","Verts/ALE","EELV","pour"],
  [65,"fr","Eva JOLY","Verts/ALE","EELV","pour"],
  [66,"fr","François ALFONSI","Verts/ALE","EELV","pour"],
  [67,"fr","Jean-Jacob BICEP","Verts/ALE","EELV","pour"],
  [68,"fr","Jean-Paul BESSET","Verts/ALE","EELV","pour"],
  [69,"fr","José BOVÉ","Verts/ALE","EELV","pour"],
  [70,"fr","Karima DELLI","Verts/ALE","EELV","pour"],
  [71,"fr","Michèle RIVASI","Verts/ALE","EELV","pour"],
  [72,"fr","Nicole KIIL-NIELSEN","Verts/ALE","EELV","pour"],
  [73,"fr","Yannick JADOT","Verts/ALE","EELV","pour"],
  [74,"fr","Yves COCHET","Verts/ALE","EELV","pour"],
  [75,"eur","Gauche unitaire européenne/Gauche verte nordique","68","GUE/NGL","pour"],
  [76,"eur","Verts européens/Alliance libre européenne","100","Verts/ALE","pour"],
  [77,"eur","Socialistes & démocrates","93","S&D","pour"],
  [78,"eur","Alliance des démocrates et des libéraux pour l'Europe","81","ADLE","pour"],
  [79,"eur","Parti populaire européen","74","PPE","contre"],
  [80,"eur","Europe libertés démocratie","91","EFD","contre"],
  [81,"eur","Conservateurs et réformistes européens","95","CRE","contre"]
]
union_bancaire = [
  [0,"fr","Sylvie GOULARD","ADLE","Modem","pour"],
  [1,"fr","Corinne LEPAGE","ADLE","Cap21","pour"],
  [2,"fr","Jean-Luc BENNAHMIAS","ADLE","Modem","pour"],
  [3,"fr","Marielle de SARNEZ","ADLE","Modem","na"],
  [4,"fr","Nathalie GRIESBECK","ADLE","Modem","pour"],
  [5,"fr","Robert ROCHEFORT","ADLE","Modem","pour"],
  [6,"fr","Philippe de VILLIERS","EFD","MPF","contre"],
  [7,"fr","Jacky HÉNIN","GUE/NGL","FdG","contre"],
  [8,"fr","Jean-Luc MÉLENCHON","GUE/NGL","FdG","contre"],
  [9,"fr","Marie-Christine VERGIAT","GUE/NGL","FdG","na"],
  [10,"fr","Patrick LE HYARIC","GUE/NGL","FdG","contre"],
  [11,"fr","Younous OMARJEE","GUE/NGL","FdG","contre"],
  [12,"fr","Jean-Marie LE PEN","NI","FN","contre"],
  [13,"fr","Marine LE PEN","NI","FN","contre"],
  [14,"fr","Bruno GOLLNISCH","NI","FN","contre"],
  [15,"fr","Michel DANTIN","PPE","UMP","pour"],
  [16,"fr","Christine DE VEYRAC","PPE","UDI","pour"],
  [17,"fr","Dominique VLASTO","PPE","UMP","pour"],
  [18,"fr","Jean ROATTA","PPE","UMP","pour"],
  [19,"fr","Brice HORTEFEUX","PPE","UMP","pour"],
  [20,"fr","Constance LE GRIP","PPE","UMP","pour"],
  [21,"fr","Gaston FRANCO","PPE","UMP","pour"],
  [22,"fr","Jean-Paul GAUZÈS","PPE","UMP","pour"],
  [23,"fr","Jean-Pierre AUDY","PPE","UMP","pour"],
  [24,"fr","Marielle GALLO","PPE","UDI","pour"],
  [25,"fr","Agnès LE BRUN","PPE","UMP","pour"],
  [26,"fr","Alain CADEC","PPE","UMP","pour"],
  [27,"fr","Alain LAMASSOURE","PPE","UMP","pour"],
  [28,"fr","Arnaud DANJEAN","PPE","UMP","pour"],
  [29,"fr","Dominique RIQUET","PPE","PR/UDI","pour"],
  [30,"fr","Elisabeth MORIN-CHARTIER","PPE","UMP","pour"],
  [31,"fr","Franck PROUST","PPE","UMP","pour"],
  [32,"fr","Françoise GROSSETÊTE","PPE","UMP","pour"],
  [33,"fr","Jean-Marie CAVADA","PPE","NC","pour"],
  [34,"fr","Joseph DAUL","PPE","UMP","pour"],
  [35,"fr","Marie-Thérèse SANCHEZ-SCHMID","PPE","UMP","pour"],
  [36,"fr","Maurice PONGA","PPE","UMP","pour"],
  [37,"fr","Michèle STRIFFLER","PPE","PR/UDI","pour"],
  [38,"fr","Nora BERRA","PPE","UMP","pour"],
  [39,"fr","Philippe BOULLAND","PPE","UMP","pour"],
  [40,"fr","Philippe JUVIN","PPE","UMP","pour"],
  [41,"fr","Rachida DATI","PPE","UMP","pour"],
  [42,"fr","Sophie AUCONIE","PPE","UDI","absent"],
  [43,"fr","Tokia SAÏFI","PPE","UMP","pour"],
  [44,"fr","Véronique MATHIEU HOUILLON","PPE","UMP","pour"],
  [45,"fr","Henri WEBER","S&D","PS","na"],
  [46,"fr","Liem HOANG NGOC","S&D","PS","pour"],
  [47,"fr","Harlem DÉSIR","S&D","PS","na"],
  [48,"fr","Eric ANDRIEU","S&D","PS","absent"],
  [49,"fr","Bernadette VERGNAUD","S&D","PS","pour"],
  [50,"fr","Catherine TRAUTMANN","S&D","PS","pour"],
  [51,"fr","Christine REVAULT D'ALLONNES BONNEFOY","S&D","PS","pour"],
  [52,"fr","Françoise CASTEX","S&D","PS","pour"],
  [53,"fr","Gilles PARGNEAUX","S&D","PS","pour"],
  [54,"fr","Isabelle THOMAS","S&D","PS","pour"],
  [55,"fr","Jean Louis COTTIGNY","S&D","PS","pour"],
  [56,"fr","Patrice TIROLIEN","S&D","PS","pour"],
  [57,"fr","Pervenche BERÈS","S&D","PS","pour"],
  [58,"fr","Sylvie GUILLAUME","S&D","PS","pour"],
  [59,"fr","Catherine GRÈZE","Verts/ALE","EELV","pour"],
  [60,"fr","Hélène FLAUTRE","Verts/ALE","EELV","pour"],
  [61,"fr","Karim ZÉRIBI","Verts/ALE","EELV","pour"],
  [62,"fr","Malika BENARAB-ATTOU","Verts/ALE","EELV","pour"],
  [63,"fr","Sandrine BÉLIER","Verts/ALE","EELV","pour"],
  [64,"fr","Daniel COHN-BENDIT","Verts/ALE","EELV","pour"],
  [65,"fr","Eva JOLY","Verts/ALE","EELV","pour"],
  [66,"fr","François ALFONSI","Verts/ALE","EELV","pour"],
  [67,"fr","Jean-Jacob BICEP","Verts/ALE","EELV","pour"],
  [68,"fr","Jean-Paul BESSET","Verts/ALE","EELV","pour"],
  [69,"fr","José BOVÉ","Verts/ALE","EELV","pour"],
  [70,"fr","Karima DELLI","Verts/ALE","EELV","pour"],
  [71,"fr","Michèle RIVASI","Verts/ALE","EELV","pour"],
  [72,"fr","Nicole KIIL-NIELSEN","Verts/ALE","EELV","pour"],
  [73,"fr","Yannick JADOT","Verts/ALE","EELV","pour"],
  [74,"fr","Yves COCHET","Verts/ALE","EELV","pour"],
  [75,"eur","Gauche unitaire européenne/Gauche verte nordique","94","GUE/NGL","contre"],
  [76,"eur","Verts européens/Alliance libre européenne","93","Verts/ALE","pour"],
  [77,"eur","Socialistes & démocrates","100","S&D","pour"],
  [78,"eur","Alliance des démocrates et des libéraux pour l'Europe","95","ADLE","pour"],
  [79,"eur","Parti populaire européen","99","PPE","pour"],
  [80,"eur","Europe libertés démocratie","75","EFD","contre"],
  [81,"eur","Conservateurs et réformistes européens","68","CRE","pour"]
]
ttip = [
  [0,"fr","Sylvie GOULARD","ADLE","Modem","abstention"],
  [1,"fr","Corinne LEPAGE","ADLE","Cap21","contre"],
  [2,"fr","Jean-Luc BENNAHMIAS","ADLE","Modem","abstention"],
  [3,"fr","Marielle de SARNEZ","ADLE","Modem","abstention"],
  [4,"fr","Nathalie GRIESBECK","ADLE","Modem","abstention"],
  [5,"fr","Robert ROCHEFORT","ADLE","Modem","abstention"],
  [6,"fr","Philippe de VILLIERS","EFD","MPF","absent"],
  [7,"fr","Jacky HÉNIN","GUE/NGL","FdG","contre"],
  [8,"fr","Jean-Luc MÉLENCHON","GUE/NGL","FdG","contre"],
  [9,"fr","Marie-Christine VERGIAT","GUE/NGL","FdG","contre"],
  [10,"fr","Patrick LE HYARIC","GUE/NGL","FdG","contre"],
  [11,"fr","Younous OMARJEE","GUE/NGL","FdG","contre"],
  [12,"fr","Jean-Marie LE PEN","NI","FN","contre"],
  [13,"fr","Marine LE PEN","NI","FN","contre"],
  [14,"fr","Bruno GOLLNISCH","NI","FN","contre"],
  [15,"fr","Michel DANTIN","PPE","UMP","pour"],
  [16,"fr","Christine DE VEYRAC","PPE","UDI","pour"],
  [17,"fr","Dominique VLASTO","PPE","UMP","pour"],
  [18,"fr","Jean ROATTA","PPE","UMP","pour"],
  [19,"fr","Brice HORTEFEUX","PPE","UMP","pour"],
  [20,"fr","Constance LE GRIP","PPE","UMP","pour"],
  [21,"fr","Gaston FRANCO","PPE","UMP","pour"],
  [22,"fr","Jean-Paul GAUZÈS","PPE","UMP","pour"],
  [23,"fr","Jean-Pierre AUDY","PPE","UMP","pour"],
  [24,"fr","Marielle GALLO","PPE","UDI","pour"],
  [25,"fr","Agnès LE BRUN","PPE","UMP","pour"],
  [26,"fr","Alain CADEC","PPE","UMP","pour"],
  [27,"fr","Alain LAMASSOURE","PPE","UMP","pour"],
  [28,"fr","Arnaud DANJEAN","PPE","UMP","pour"],
  [29,"fr","Dominique RIQUET","PPE","PR/UDI","pour"],
  [30,"fr","Elisabeth MORIN-CHARTIER","PPE","UMP","pour"],
  [31,"fr","Franck PROUST","PPE","UMP","pour"],
  [32,"fr","Françoise GROSSETÊTE","PPE","UMP","pour"],
  [33,"fr","Jean-Marie CAVADA","PPE","NC","pour"],
  [34,"fr","Joseph DAUL","PPE","UMP","pour"],
  [35,"fr","Marie-Thérèse SANCHEZ-SCHMID","PPE","UMP","pour"],
  [36,"fr","Maurice PONGA","PPE","UMP","pour"],
  [37,"fr","Michèle STRIFFLER","PPE","PR/UDI","pour"],
  [38,"fr","Nora BERRA","PPE","UMP","pour"],
  [39,"fr","Philippe BOULLAND","PPE","UMP","pour"],
  [40,"fr","Philippe JUVIN","PPE","UMP","pour"],
  [41,"fr","Rachida DATI","PPE","UMP","pour"],
  [42,"fr","Sophie AUCONIE","PPE","UDI","pour"],
  [43,"fr","Tokia SAÏFI","PPE","UMP","pour"],
  [44,"fr","Véronique MATHIEU HOUILLON","PPE","UMP","na"],
  [45,"fr","Henri WEBER","S&D","PS","abstention"],
  [46,"fr","Liem HOANG NGOC","S&D","PS","abstention"],
  [47,"fr","Harlem DÉSIR","S&D","PS","absent"],
  [48,"fr","Eric ANDRIEU","S&D","PS","abstention"],
  [49,"fr","Bernadette VERGNAUD","S&D","PS","abstention"],
  [50,"fr","Catherine TRAUTMANN","S&D","PS","abstention"],
  [51,"fr","Christine REVAULT D'ALLONNES BONNEFOY","S&D","PS","abstention"],
  [52,"fr","Françoise CASTEX","S&D","PS","contre"],
  [53,"fr","Gilles PARGNEAUX","S&D","PS","abstention"],
  [54,"fr","Isabelle THOMAS","S&D","PS","contre"],
  [55,"fr","Jean Louis COTTIGNY","S&D","PS","abstention"],
  [56,"fr","Patrice TIROLIEN","S&D","PS","absent"],
  [57,"fr","Pervenche BERÈS","S&D","PS","abstention"],
  [58,"fr","Sylvie GUILLAUME","S&D","PS","abstention"],
  [59,"fr","Catherine GRÈZE","Verts/ALE","EELV","contre"],
  [60,"fr","Hélène FLAUTRE","Verts/ALE","EELV","absent"],
  [61,"fr","Karim ZÉRIBI","Verts/ALE","EELV","absent"],
  [62,"fr","Malika BENARAB-ATTOU","Verts/ALE","EELV","contre"],
  [63,"fr","Sandrine BÉLIER","Verts/ALE","EELV","contre"],
  [64,"fr","Daniel COHN-BENDIT","Verts/ALE","EELV","contre"],
  [65,"fr","Eva JOLY","Verts/ALE","EELV","contre"],
  [66,"fr","François ALFONSI","Verts/ALE","EELV","contre"],
  [67,"fr","Jean-Jacob BICEP","Verts/ALE","EELV","absent"],
  [68,"fr","Jean-Paul BESSET","Verts/ALE","EELV","contre"],
  [69,"fr","José BOVÉ","Verts/ALE","EELV","contre"],
  [70,"fr","Karima DELLI","Verts/ALE","EELV","contre"],
  [71,"fr","Michèle RIVASI","Verts/ALE","EELV","contre"],
  [72,"fr","Nicole KIIL-NIELSEN","Verts/ALE","EELV","contre"],
  [73,"fr","Yannick JADOT","Verts/ALE","EELV","contre"],
  [74,"fr","Yves COCHET","Verts/ALE","EELV","absent"],
  [75,"eur","Gauche unitaire européenne/Gauche verte nordique","100","GUE/NGL","contre"],
  [76,"eur","Verts européens/Alliance libre européenne","91","Verts/ALE","contre"],
  [77,"eur","Socialistes & démocrates","88","S&D","pour"],
  [78,"eur","Alliance des démocrates et des libéraux pour l'Europe","89","ADLE","pour"],
  [79,"eur","Parti populaire européen","98","PPE","pour"],
  [80,"eur","Europe libertés démocratie","78","EFD","pour"],
  [81,"eur","Conservateurs et réformistes européens","100","CRE","pour"]
]
protection_donnees = [
  [0,"fr","Sylvie GOULARD","ADLE","Modem","pour"],
  [1,"fr","Corinne LEPAGE","ADLE","Cap21","pour"],
  [2,"fr","Jean-Luc BENNAHMIAS","ADLE","Modem","pour"],
  [3,"fr","Marielle de SARNEZ","ADLE","Modem","pour"],
  [4,"fr","Nathalie GRIESBECK","ADLE","Modem","pour"],
  [5,"fr","Robert ROCHEFORT","ADLE","Modem","pour"],
  [6,"fr","Philippe de VILLIERS","EFD","MPF","absent"],
  [7,"fr","Jacky HÉNIN","GUE/NGL","FdG","absent"],
  [8,"fr","Jean-Luc MÉLENCHON","GUE/NGL","FdG","pour"],
  [9,"fr","Marie-Christine VERGIAT","GUE/NGL","FdG","pour"],
  [10,"fr","Patrick LE HYARIC","GUE/NGL","FdG","pour"],
  [11,"fr","Younous OMARJEE","GUE/NGL","FdG","pour"],
  [12,"fr","Jean-Marie LE PEN","NI","FN","abstention"],
  [13,"fr","Marine LE PEN","NI","FN","na"],
  [14,"fr","Bruno GOLLNISCH","NI","FN","pour"],
  [15,"fr","Michel DANTIN","PPE","UMP","absent"],
  [16,"fr","Christine DE VEYRAC","PPE","UDI","absent"],
  [17,"fr","Dominique VLASTO","PPE","UMP","absent"],
  [18,"fr","Jean ROATTA","PPE","UMP","absent"],
  [19,"fr","Brice HORTEFEUX","PPE","UMP","pour"],
  [20,"fr","Constance LE GRIP","PPE","UMP","pour"],
  [21,"fr","Gaston FRANCO","PPE","UMP","pour"],
  [22,"fr","Jean-Paul GAUZÈS","PPE","UMP","pour"],
  [23,"fr","Jean-Pierre AUDY","PPE","UMP","pour"],
  [24,"fr","Marielle GALLO","PPE","UDI","pour"],
  [25,"fr","Agnès LE BRUN","PPE","UMP","pour"],
  [26,"fr","Alain CADEC","PPE","UMP","pour"],
  [27,"fr","Alain LAMASSOURE","PPE","UMP","pour"],
  [28,"fr","Arnaud DANJEAN","PPE","UMP","pour"],
  [29,"fr","Dominique RIQUET","PPE","PR/UDI","pour"],
  [30,"fr","Elisabeth MORIN-CHARTIER","PPE","UMP","pour"],
  [31,"fr","Franck PROUST","PPE","UMP","pour"],
  [32,"fr","Françoise GROSSETÊTE","PPE","UMP","pour"],
  [33,"fr","Jean-Marie CAVADA","PPE","NC","pour"],
  [34,"fr","Joseph DAUL","PPE","UMP","na"],
  [35,"fr","Marie-Thérèse SANCHEZ-SCHMID","PPE","UMP","pour"],
  [36,"fr","Maurice PONGA","PPE","UMP","pour"],
  [37,"fr","Michèle STRIFFLER","PPE","PR/UDI","pour"],
  [38,"fr","Nora BERRA","PPE","UMP","pour"],
  [39,"fr","Philippe BOULLAND","PPE","UMP","pour"],
  [40,"fr","Philippe JUVIN","PPE","UMP","pour"],
  [41,"fr","Rachida DATI","PPE","UMP","pour"],
  [42,"fr","Sophie AUCONIE","PPE","UDI","pour"],
  [43,"fr","Tokia SAÏFI","PPE","UMP","pour"],
  [44,"fr","Véronique MATHIEU HOUILLON","PPE","UMP","pour"],
  [45,"fr","Henri WEBER","S&D","PS","absent"],
  [46,"fr","Liem HOANG NGOC","S&D","PS","na"],
  [47,"fr","Harlem DÉSIR","S&D","PS","na"],
  [48,"fr","Eric ANDRIEU","S&D","PS","pour"],
  [49,"fr","Bernadette VERGNAUD","S&D","PS","pour"],
  [50,"fr","Catherine TRAUTMANN","S&D","PS","pour"],
  [51,"fr","Christine REVAULT D'ALLONNES BONNEFOY","S&D","PS","pour"],
  [52,"fr","Françoise CASTEX","S&D","PS","pour"],
  [53,"fr","Gilles PARGNEAUX","S&D","PS","pour"],
  [54,"fr","Isabelle THOMAS","S&D","PS","pour"],
  [55,"fr","Jean Louis COTTIGNY","S&D","PS","pour"],
  [56,"fr","Patrice TIROLIEN","S&D","PS","pour"],
  [57,"fr","Pervenche BERÈS","S&D","PS","pour"],
  [58,"fr","Sylvie GUILLAUME","S&D","PS","pour"],
  [59,"fr","Catherine GRÈZE","Verts/ALE","EELV","absent"],
  [60,"fr","Hélène FLAUTRE","Verts/ALE","EELV","absent"],
  [61,"fr","Karim ZÉRIBI","Verts/ALE","EELV","absent"],
  [62,"fr","Malika BENARAB-ATTOU","Verts/ALE","EELV","pour"],
  [63,"fr","Sandrine BÉLIER","Verts/ALE","EELV","pour"],
  [64,"fr","Daniel COHN-BENDIT","Verts/ALE","EELV","pour"],
  [65,"fr","Eva JOLY","Verts/ALE","EELV","pour"],
  [66,"fr","François ALFONSI","Verts/ALE","EELV","pour"],
  [67,"fr","Jean-Jacob BICEP","Verts/ALE","EELV","pour"],
  [68,"fr","Jean-Paul BESSET","Verts/ALE","EELV","pour"],
  [69,"fr","José BOVÉ","Verts/ALE","EELV","pour"],
  [70,"fr","Karima DELLI","Verts/ALE","EELV","pour"],
  [71,"fr","Michèle RIVASI","Verts/ALE","EELV","pour"],
  [72,"fr","Nicole KIIL-NIELSEN","Verts/ALE","EELV","pour"],
  [73,"fr","Yannick JADOT","Verts/ALE","EELV","pour"],
  [74,"fr","Yves COCHET","Verts/ALE","EELV","pour"],
  [75,"eur","Gauche unitaire européenne/Gauche verte nordique","94","GUE/NGL","pour"],
  [76,"eur","Verts européens/Alliance libre européenne","100","Verts/ALE","pour"],
  [77,"eur","Socialistes & démocrates","94","S&D","pour"],
  [78,"eur","Alliance des démocrates et des libéraux pour l'Europe","99","ADLE","pour"],
  [79,"eur","Parti populaire européen","100","PPE","pour"],
  [80,"eur","Europe libertés démocratie","60","EFD","pour"],
  [81,"eur","Conservateurs et réformistes européens","100","CRE","pour"]
]
travailleurs_detaches = [
  [0,"fr","Sylvie GOULARD","ADLE","Modem","pour"],
  [1,"fr","Corinne LEPAGE","ADLE","Cap21","pour"],
  [2,"fr","Jean-Luc BENNAHMIAS","ADLE","Modem","contre"],
  [3,"fr","Marielle de SARNEZ","ADLE","Modem","pour"],
  [4,"fr","Nathalie GRIESBECK","ADLE","Modem","pour"],
  [5,"fr","Robert ROCHEFORT","ADLE","Modem","absent"],
  [6,"fr","Philippe de VILLIERS","EFD","MPF","contre"],
  [7,"fr","Jacky HÉNIN","GUE/NGL","FdG","contre"],
  [8,"fr","Jean-Luc MÉLENCHON","GUE/NGL","FdG","contre"],
  [9,"fr","Marie-Christine VERGIAT","GUE/NGL","FdG","contre"],
  [10,"fr","Patrick LE HYARIC","GUE/NGL","FdG","contre"],
  [11,"fr","Younous OMARJEE","GUE/NGL","FdG","contre"],
  [12,"fr","Jean-Marie LE PEN","NI","FN","abstention"],
  [13,"fr","Marine LE PEN","NI","FN","abstention"],
  [14,"fr","Bruno GOLLNISCH","NI","FN","abstention"],
  [15,"fr","Michel DANTIN","PPE","UMP","pour"],
  [16,"fr","Christine DE VEYRAC","PPE","UDI","pour"],
  [17,"fr","Dominique VLASTO","PPE","UMP","pour"],
  [18,"fr","Jean ROATTA","PPE","UMP","absent"],
  [19,"fr","Brice HORTEFEUX","PPE","UMP","pour"],
  [20,"fr","Constance LE GRIP","PPE","UMP","pour"],
  [21,"fr","Gaston FRANCO","PPE","UMP","pour"],
  [22,"fr","Jean-Paul GAUZÈS","PPE","UMP","pour"],
  [23,"fr","Jean-Pierre AUDY","PPE","UMP","pour"],
  [24,"fr","Marielle GALLO","PPE","UDI","pour"],
  [25,"fr","Agnès LE BRUN","PPE","UMP","pour"],
  [26,"fr","Alain CADEC","PPE","UMP","pour"],
  [27,"fr","Alain LAMASSOURE","PPE","UMP","pour"],
  [28,"fr","Arnaud DANJEAN","PPE","UMP","pour"],
  [29,"fr","Dominique RIQUET","PPE","PR/UDI","pour"],
  [30,"fr","Elisabeth MORIN-CHARTIER","PPE","UMP","pour"],
  [31,"fr","Franck PROUST","PPE","UMP","pour"],
  [32,"fr","Françoise GROSSETÊTE","PPE","UMP","pour"],
  [33,"fr","Jean-Marie CAVADA","PPE","NC","pour"],
  [34,"fr","Joseph DAUL","PPE","UMP","pour"],
  [35,"fr","Marie-Thérèse SANCHEZ-SCHMID","PPE","UMP","pour"],
  [36,"fr","Maurice PONGA","PPE","UMP","pour"],
  [37,"fr","Michèle STRIFFLER","PPE","PR/UDI","pour"],
  [38,"fr","Nora BERRA","PPE","UMP","absent"],
  [39,"fr","Philippe BOULLAND","PPE","UMP","pour"],
  [40,"fr","Philippe JUVIN","PPE","UMP","pour"],
  [41,"fr","Rachida DATI","PPE","UMP","pour"],
  [42,"fr","Sophie AUCONIE","PPE","UDI","pour"],
  [43,"fr","Tokia SAÏFI","PPE","UMP","pour"],
  [44,"fr","Véronique MATHIEU HOUILLON","PPE","UMP","pour"],
  [45,"fr","Henri WEBER","S&D","PS","absent"],
  [46,"fr","Liem HOANG NGOC","S&D","PS","pour"],
  [47,"fr","Harlem DÉSIR","S&D","PS","na"],
  [48,"fr","Eric ANDRIEU","S&D","PS","pour"],
  [49,"fr","Bernadette VERGNAUD","S&D","PS","pour"],
  [50,"fr","Catherine TRAUTMANN","S&D","PS","pour"],
  [51,"fr","Christine REVAULT D'ALLONNES BONNEFOY","S&D","PS","na"],
  [52,"fr","Françoise CASTEX","S&D","PS","pour"],
  [53,"fr","Gilles PARGNEAUX","S&D","PS","pour"],
  [54,"fr","Isabelle THOMAS","S&D","PS","pour"],
  [55,"fr","Jean Louis COTTIGNY","S&D","PS","pour"],
  [56,"fr","Patrice TIROLIEN","S&D","PS","pour"],
  [57,"fr","Pervenche BERÈS","S&D","PS","pour"],
  [58,"fr","Sylvie GUILLAUME","S&D","PS","pour"],
  [59,"fr","Catherine GRÈZE","Verts/ALE","EELV","pour"],
  [60,"fr","Hélène FLAUTRE","Verts/ALE","EELV","pour"],
  [61,"fr","Karim ZÉRIBI","Verts/ALE","EELV","pour"],
  [62,"fr","Malika BENARAB-ATTOU","Verts/ALE","EELV","pour"],
  [63,"fr","Sandrine BÉLIER","Verts/ALE","EELV","pour"],
  [64,"fr","Daniel COHN-BENDIT","Verts/ALE","EELV","pour"],
  [65,"fr","Eva JOLY","Verts/ALE","EELV","pour"],
  [66,"fr","François ALFONSI","Verts/ALE","EELV","pour"],
  [67,"fr","Jean-Jacob BICEP","Verts/ALE","EELV","pour"],
  [68,"fr","Jean-Paul BESSET","Verts/ALE","EELV","pour"],
  [69,"fr","José BOVÉ","Verts/ALE","EELV","pour"],
  [70,"fr","Karima DELLI","Verts/ALE","EELV","pour"],
  [71,"fr","Michèle RIVASI","Verts/ALE","EELV","pour"],
  [72,"fr","Nicole KIIL-NIELSEN","Verts/ALE","EELV","pour"],
  [73,"fr","Yannick JADOT","Verts/ALE","EELV","pour"],
  [74,"fr","Yves COCHET","Verts/ALE","EELV","pour"],
  [75,"eur","Gauche unitaire européenne/Gauche verte nordique","97","GUE/NGL","contre"],
  [76,"eur","Verts européens/Alliance libre européenne","95","Verts/ALE","pour"],
  [77,"eur","Socialistes & démocrates","52","S&D","contre"],
  [78,"eur","Alliance des démocrates et des libéraux pour l'Europe","96","ADLE","pour"],
  [79,"eur","Parti populaire européen","95","PPE","pour"],
  [80,"eur","Europe libertés démocratie","33","EFD","contre"],
  [81,"eur","Conservateurs et réformistes européens","98","CRE","pour"]
]
votes = {
"climat":"le paquet climat-énergie",
"union_bancaire" : "la résolution pour l'union bancaire",
"protection_donnees": "la résolution sur la protection des données",
"travailleurs_detaches": "la résolution sur les travailleurs détachés",
"ttip": "la résolution sur ma négociation du traité de libre-échange avec les Etats-Unis (Tafta)",
"absent": "900,150",
"na": "900,150"
}
centre_fr = {
"pour":"300,150",
"abstention" : "500,150",
"contre": "700,150",
"absent": "900,150",
"na": "900,150"
}
centre_eur = {
"pour":"300,320",
"abstention" : "500,320",
"contre": "700,320"
}

textes = [
  ["Députés français",10,170,"tt3_capital"],
  ["Groupes européens",10,350,"tt3_capital"],
  ["Pour",280,40,"tt4_capital"],
  ["Abstention",460,40,"tt4_capital"],
  ["Contre",680,40,"tt4_capital"],
  ["Absent", 880,40,"tt4_capital"],
];
couleurs = {
// FRANCE
"FdG":"#D40000",
"FN" : "#04103f",
"EELV": "#80b904",
"UMP": "#2c59a8",
"UDI": "#71589E",
"PR/UDI": "#71589E",
"NC":"#71589E",
"PS": "#f96996",
"Modem": "#fb6b02",
"Cap21":"#fb6b02",
"MPF":"#28beaa",
// EUROPE
"PPE": "#2c59a8",
"Verts/ALE": "#80b904",
"S&D": "#f96996",
"GUE/NGL":"#D40000",
"ADLE": "#fb6b02",
"EFD":"#28beaa",
"CRE":"#c3ad17",
"NI":"#A2A9AE"
}
partis = {
// FRANCE
"FdG":"Front de gauche",
"FN" : "Front national",
"EELV": "Europe Ecologie-Les Verts",
"UMP": "Union pour un mouvement populaire",
"UDI": "Union des démocrates et indépendants",
"PR/UDI": "radical/Union des démocrates et indépendants",
"NC":"Nouveau Centre",
"PS": "socialiste",
"Modem": "Mouvement démocrate",
"Cap21":"Citoyenneté Action Participation pour le 21ème siècle",
"MPF":"Mouvement pour la France",
// EUROPE
"PPE": "groupe du Parti Populaire Européen",
"Verts/ALE": "groupe des Verts/Alliance libre européenne",
"S&D": "groupe de l'Alliance Progressiste des Socialistes et Démocrates",
"GUE/NGL":"groupe confédéral de la Gauche unitaire européenne/Gauche verte nordique",
"ADLE": "groupe de l'Alliance des démocrates et des libéraux pour l'Europe",
"EFD": "groupe Europe libertés démocratie",
"CRE":"groupe des conservateurs et réformistes européens",
"NI":"groupe des non-inscrits"
};
rayons = {
"fr":10,
"eur" : 20
};
